### ISSUE TITLE
How easy would it be to add the CrashReportSender class?

### ISSUE THREAD

**Issue by tonyvsuk** [getsentry/breakpad-tools#3]
Forst of all, thanks for your work. I had already managed to get Breakpad working on Windows, but really struggled with the Mac.

Would it be easy to add in the CrashReportSender class? 

Thanks in advance,
 
Tony.

**Comment by tonyvsuk** [comment]
Not to worry, I found cpp-httplib on github, that allows the same functionality.

Tony.

**Comment by Swatinem** [comment]
I don’t think we will do any more work on these tools here.
