### ISSUE TITLE
dwarf2reader::ByteReader::SetAddressSize(uint8): Assertion `size == 4 || size == 8' failed.

### ISSUE THREAD

**Issue by qknight** [getsentry/breakpad-tools#4]
### Environment clang++

docker container ubuntu:focal with clang-14 (clang-14 is the default).

```
docker run -it ubuntu:focal
root@fea6291a7c1b:/# 
apt update
apt install clang++
```

Note: I tested  wget https://s3.amazonaws.com/getsentry-builds/getsentry/breakpad-tools/breakpad-tools-linux.zip as well as a custom linux build from breakpad-tools on this very ubuntu:focal platform. Both times the same result.

### Steps to Reproduce

Using this program:
```
test.cpp
#include <iostream>

int main() {

std::cout << "hello world" << std::endl;
}
```

Creating test

`clang++ test.cpp -g -O0 -o test`

Then finally:

```
dump_syms -i test
MODULE Linux x86_64 AE4C641CFA3D4AEF00000000000000000 test
INFO CODE_ID 1C644CAE3DFAEF4A

dump_syms -v test
dump_syms: ../deps/breakpad/src/common/dwarf/bytereader.cc:58: void dwarf2reader::ByteReader::SetAddressSize(uint8): Assertion `size == 4 || size == 8' failed.
Aborted
```

See also https://chromium.googlesource.com/breakpad/breakpad/+/97a98836768f8f0154f8f86e5e14c2bb7e74132e/src/common/dwarf/bytereader.cc#58 

### Expected Result

My expectation was that the debug symbols from test are extracted into test.sym for later breakpad dump analysis.

### Actual Result

dump_syms: ../deps/breakpad/src/common/dwarf/bytereader.cc:58: void dwarf2reader::ByteReader::SetAddressSize(uint8): Assertion `size == 4 || size == 8' failed.

# g++ 9.4.0

```
g++ --version
g++ (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0

g++ test.cpp -g -O0 -o test

dump_syms test
MODULE Linux x86_64 84E1D8C2B969503400000000000000000 test
INFO CODE_ID C2D8E18469B93450
FILE 0 /tmp/test.cpp
FILE 1 /usr/include/c++/9/iostream
FUNC 1a79 37 0 main
1a79 8 3 0
1a81 16 5 0
1a97 12 5 0
1aa9 7 6 0
FUNC 1ab0 4d 0 __static_initialization_and_destruction_0
1ab0 12 6 0
1ac2 6 6 0
1ac8 9 6 0
1ad1 29 74 1
1afa 3 6 0
FUNC 1afd 19 0 _GLOBAL__sub_I_main
1afd 8 6 0
1b05 11 6 0
PUBLIC 1990 0 _start
PUBLIC 19c0 0 deregister_tm_clones
PUBLIC 19f0 0 register_tm_clones
PUBLIC 1a30 0 __do_global_dtors_aux
PUBLIC 1a70 0 frame_dummy
PUBLIC 1a79 0 main
PUBLIC 1ab0 0 __static_initialization_and_destruction_0(int, int)
PUBLIC 1afd 0 _GLOBAL__sub_I_main
PUBLIC 1b20 0 __libc_csu_init
PUBLIC 1b90 0 __libc_csu_fini
PUBLIC 1b98 0 _init
PUBLIC 1bb4 0 _fini
STACK CFI INIT 1990 2f .cfa: $rsp 8 + .ra: .cfa -8 + ^
STACK CFI INIT 1a79 37 .cfa: $rsp 8 + .ra: .cfa -8 + ^
STACK CFI 1a7e $rbp: .cfa -16 + ^ .cfa: $rsp 16 +
STACK CFI 1a81 .cfa: $rbp 16 +
STACK CFI 1aaf .cfa: $rsp 8 +
STACK CFI INIT 1ab0 4d .cfa: $rsp 8 + .ra: .cfa -8 + ^
STACK CFI 1ab5 $rbp: .cfa -16 + ^ .cfa: $rsp 16 +
STACK CFI 1ab8 .cfa: $rbp 16 +
STACK CFI 1afc .cfa: $rsp 8 +
STACK CFI INIT 1afd 19 .cfa: $rsp 8 + .ra: .cfa -8 + ^
STACK CFI 1b02 $rbp: .cfa -16 + ^ .cfa: $rsp 16 +
STACK CFI 1b05 .cfa: $rbp 16 +
STACK CFI 1b15 .cfa: $rsp 8 +
STACK CFI INIT 1b20 65 .cfa: $rsp 8 + .ra: .cfa -8 + ^
STACK CFI 1b26 $r15: .cfa -16 + ^ .cfa: $rsp 16 +
STACK CFI 1b2f $r14: .cfa -24 + ^ .cfa: $rsp 24 +
STACK CFI 1b34 $r13: .cfa -32 + ^ .cfa: $rsp 32 +
STACK CFI 1b39 $r12: .cfa -40 + ^ .cfa: $rsp 40 +
STACK CFI 1b3d $rbp: .cfa -48 + ^ .cfa: $rsp 48 +
STACK CFI 1b45 $rbx: .cfa -56 + ^ .cfa: $rsp 56 +
STACK CFI 1b4c .cfa: $rsp 64 +
STACK CFI 1b7a .cfa: $rsp 56 +
STACK CFI 1b7b .cfa: $rsp 48 +
STACK CFI 1b7c .cfa: $rsp 40 +
STACK CFI 1b7e .cfa: $rsp 32 +
STACK CFI 1b80 .cfa: $rsp 24 +
STACK CFI 1b82 .cfa: $rsp 16 +
STACK CFI 1b84 .cfa: $rsp 8 +
STACK CFI INIT 1b90 5 .cfa: $rsp 8 + .ra: .cfa -8 + ^
```

# clang++ using different dwarf version

if using a different dwarf format, see https://clang.llvm.org/docs/ClangCommandLineReference.html#kind-and-level-of-debug-information

clang++ test.cpp -g -O0  -gdwarf-4 -o test
dump_syms test
MODULE Linux x86_64 7341980D4D095BA400000000000000000 test
INFO CODE_ID 0D984173094DA45B
FILE 0 /tmp/test.cpp
FILE 1 /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/iostream
FUNC 1a00 2a 0 main
1a00 4 3 0
1a04 16 5 0
1a1a c 5 0
1a26 4 6 0
FUNC 1a30 2c 0 __cxx_global_var_init
1a30 4 0 0
1a34 c 74 1
1a40 1a 0 0
1a5a 2 74 1
FUNC 1a60 b 0 <name omitted>
1a60 b 0 0
PUBLIC 1910 0 _start
PUBLIC 1940 0 deregister_tm_clones
PUBLIC 1970 0 register_tm_clones
PUBLIC 19b0 0 __do_global_dtors_aux
PUBLIC 19f0 0 frame_dummy
PUBLIC 1a00 0 main
PUBLIC 1a30 0 __cxx_global_var_init
PUBLIC 1a60 0 _GLOBAL__sub_I_test.cpp
PUBLIC 1a70 0 __libc_csu_init
PUBLIC 1ae0 0 __libc_csu_fini
PUBLIC 1ae8 0 _init
PUBLIC 1b04 0 _fini
STACK CFI INIT 1910 2f .cfa: $rsp 8 + .ra: .cfa -8 + ^
STACK CFI INIT 1a30 2c .cfa: $rsp 8 + .ra: .cfa -8 + ^
STACK CFI 1a31 $rbp: .cfa -16 + ^ .cfa: $rsp 16 +
STACK CFI 1a34 .cfa: $rbp 16 +
STACK CFI 1a5b .cfa: $rsp 8 +
STACK CFI INIT 1a00 2a .cfa: $rsp 8 + .ra: .cfa -8 + ^
STACK CFI 1a01 $rbp: .cfa -16 + ^ .cfa: $rsp 16 +
STACK CFI 1a04 .cfa: $rbp 16 +
STACK CFI 1a29 .cfa: $rsp 8 +
STACK CFI INIT 1a60 b .cfa: $rsp 8 + .ra: .cfa -8 + ^
STACK CFI 1a61 $rbp: .cfa -16 + ^ .cfa: $rsp 16 +
STACK CFI 1a64 .cfa: $rbp 16 +
STACK CFI 1a6a .cfa: $rsp 8 +
STACK CFI INIT 1a70 65 .cfa: $rsp 8 + .ra: .cfa -8 + ^
STACK CFI 1a76 $r15: .cfa -16 + ^ .cfa: $rsp 16 +
STACK CFI 1a7f $r14: .cfa -24 + ^ .cfa: $rsp 24 +
STACK CFI 1a84 $r13: .cfa -32 + ^ .cfa: $rsp 32 +
STACK CFI 1a89 $r12: .cfa -40 + ^ .cfa: $rsp 40 +
STACK CFI 1a8d $rbp: .cfa -48 + ^ .cfa: $rsp 48 +
STACK CFI 1a95 $rbx: .cfa -56 + ^ .cfa: $rsp 56 +
STACK CFI 1a9c .cfa: $rsp 64 +
STACK CFI 1aca .cfa: $rsp 56 +
STACK CFI 1acb .cfa: $rsp 48 +
STACK CFI 1acc .cfa: $rsp 40 +
STACK CFI 1ace .cfa: $rsp 32 +
STACK CFI 1ad0 .cfa: $rsp 24 +
STACK CFI 1ad2 .cfa: $rsp 16 +
STACK CFI 1ad4 .cfa: $rsp 8 +
STACK CFI INIT 1ae0 5 .cfa: $rsp 8 + .ra: .cfa -8 + ^

In https://releases.llvm.org/14.0.0/tools/clang/docs/ReleaseNotes.html#dwarf-support-in-clang they write:

> The default DWARF version has increased from DWARFv4 to DWARFv5. You can opt back in to the old behavior with -gdwarf-4 or -fdebug-default-version=4. Some platforms (Darwin, Android, and SCE for instance) already opt out of this version bump as is suitable for the platform

So dump_syms needs a more recent dwarf support of some sort?

**Comment by Swatinem** [comment]
I don’t think we actively maintain this anymore.
All the sentry infrastructure can deal with native debug formats (and DWARF 5) just fine, there is no need to go via the intermediate breakpad sym format.

If you do need that for some reason, you can build the upstream code from the breakpad repo directly.

**Comment by qknight** [comment]
I don't use a _sentry infrastructure_ so I probably have to use the upstream you mentioned. Thanks for your help anyway!

Update: I've now built https://chromium.googlesource.com/breakpad/breakpad from source and it understands DWARF 5 so I'll use that from now on.

This is the draft for my multi-stage build in docker:

```
# https://docs.docker.com/language/golang/build-images/
FROM registry.internal.com:clang-builder AS breakpad-builder

WORKDIR /build

RUN git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git

ENV PATH "$PATH:/build/depot_tools"

RUN mkdir breakpad && cd breakpad && fetch breakpad && cd src && ./configure && make && make check && DESTDIR=/bp make install

## Deploy
FROM ubuntu:focal

COPY --from=breakpad-builder /bp/* /breakpad

ENV PATH "$PATH:/breakpad/local/bin"
```

# build

```
docker build -t breakpad .

docker run -it breakpad /bin/bash
root@20a831381754:/# dump_syms
Usage: dump_syms [OPTION] <binary-with-debugging-info> [directories-for-debug-file]

Options:
  -i:         Output module header information only.
  -c          Do not generate CFI section
  -d          Generate INLINE/INLINE_ORIGIN records
  -r          Do not handle inter-compilation unit references
  -v          Print all warnings to stderr
  -n <name>   Use specified name for name of the object
  -o <os>     Use specified name for the operating system
  -m          Enable writing the optional 'm' field on FUNCand PUBLIC, denoting multiple symbols for the address.
```
